const BASE_ACTIVITY_SCHEMA = "BASE_ACTIVITY_SUMMARY";
const ACTIVITY_SCHEMA = "HUAMI_EXTENDED_ACTIVITY_SAMPLE";
const HEART_RATE_RESTING_SCHEMA = "HUAMI_HEART_RATE_RESTING_SAMPLE";
const STRESS_SCHEMA = "HUAMI_STRESS_SAMPLE";
const SPO2_SCHEMA = "HUAMI_SPO2_SAMPLE";
const PAI_SCHEMA = "HUAMI_PAI_SAMPLE";
const SLEEP_RESPIRATORY_RATE_SCHEMA = "HUAMI_SLEEP_RESPIRATORY_RATE_SAMPLE";

export {
  ACTIVITY_SCHEMA,
  BASE_ACTIVITY_SCHEMA,
  HEART_RATE_RESTING_SCHEMA,
  PAI_SCHEMA,
  SLEEP_RESPIRATORY_RATE_SCHEMA,
  SPO2_SCHEMA,
  STRESS_SCHEMA,
};
